//
//  Language.swift
//  NewsApp
//
//  Created by Imen Ksouri on 05/04/2023.
//

import Foundation

enum Language: String, CaseIterable {
    case all = " All languages"
    case af = "Afrikaans"
    case ar = "Arabic"
    case bg = "Bulgarian"
    case bn = "Bengali"
    case ca = "Catalan"
    case cs = "Czech"
    case cy = "Welsh"
    case cn = "Chinese"
    case da = "Danish"
    case de = "German"
    case el = "Greek"
    case en = "English"
    case es = "Spanish"
    case et = "Estonian"
    case fa = "Persian"
    case fi = "Finnish"
    case fr = "French"
    case gu = "Gujarati"
    case he = "Hebrew"
    case hi = "Hindi"
    case hr = "Croatian"
    case hu = "Hungarian"
    case id = "Indonesian"
    case it = "Italian"
    case ja = "Japanese"
    case kn = "Kannada"
    case ko = "Korean"
    case lt = "Lithuanian"
    case lv = "Latvian"
    case mk = "Macedonian"
    case ml = "Malayalam"
    case mr = "Marathi"
    case ne = "Nepali"
    case nl = "Dutch"
    case no = "Norwegian"
    case pa = "Panjabi"
    case pl = "Polish"
    case pt = "Portuguese"
    case ro = "Romanian"
    case ru = "Russian"
    case sk = "Slovak"
    case sl = "Slovenian"
    case so = "Somali"
    case sq = "Albanian"
    case sv = "Swedish"
    case sw = "Swahili"
    case ta = "Tamil"
    case te = "Telugu"
    case th = "Thai"
    case tl = "Tagalog"
    case tr = "Turkish"
    case tw = "Twi"
    case uk = "Ukrainian"
    case ur = "Urdu"
    case vi = "Vietnamese"
}
