//
//  Model.swift
//  NewsApp
//
//  Created by Imen Ksouri on 04/04/2023.
//

import Foundation

#if DEBUG
extension Article {
    static let sampleArticle1 = Article(title: "The Apple Watch Ultra Is Cheaper Than Ever",
                                 author: "Tucker Bowe",
                                 published_date: "2023-04-04 00:44:00",
                                 link: "https://www.menshealth.com/technology-gear/a43501125/apple-watch-deals-march-2023/",
                                 clean_url: "menshealth.com",
                                 excerpt: "We round up the best deals on every Apple Watch model that has been released in the last few years.",
                                 summary: "It's 2023 and Apple sells three different smartwatches. There's the Apple Watch Series 8, which looks very similar to last year's Series but adds a few key health and wellness features. There's the Apple Watch SE (Gen 2), which is very similar to the Series 8 but lacks an always-on display and few key sensors; it's currently the most affordable Apple Watch that Apple sells. And then there's Apple Watch Ultra, which is Apple's most rugged, capable and expensive smartwatch ever. The Apple Watches Here's a quick rundown of the three Apple Watch models that Apple currently sells: Apple doesn't sell its older Apple Watch models anymore, which now includes the Series 1 through the 2021-released Series 7.",
                                 topic: "entertainment",
                                 country: "US",
                                 language: "en",
                                 media: "https://hips.hearstapps.com/hmg-prod/images/download-642b728745409.jpeg?crop=1xw:1xh;center,top&resize=640:*")
    
    static let sampleArticle2 = Article(title: "Apple Pay network experienced intermittent outage",
                                 author: "",
                                 published_date: "2023-03-30 02:30:00",
                                 link: "https://forums.appleinsider.com/discussion/231427",
                                 clean_url: "appleinsider.com",
                                 excerpt: "Some users reported Apple Pay services were down, from Apple Cash to Apple Card, and Apple has since resolved the problem. Apple Pay and Wallet is down Apple Pay and Apple Wallet went down around 4:15…",
                                 summary: "Some users reported Apple Pay services were down, from Apple Cash to Apple Card, and Apple has since resolved the problem. Apple Pay and Wallet is down Apple Pay and Apple Wallet went down around 4:15 p.m. EST on Wednesday. The outage prevented certain Apple Pay transactions or payments to the Apple Card from working. Apple's services status page briefly reflected that Apple Pay services were experiencing an outage. The status indicator flashed back and forth between issue and available until it was resolved.",
                                 topic: "news",
                                 country: "US",
                                 language: "en",
                                 media: "https://photos5.appleinsider.com/gallery/53723-108018-Pay-down-xl.jpg")
    
    static let sampleArticle3 = Article(title: "Apple teases its first official Apple Store in India, flagship store to open in Mumbai's BKC",
                                 author: "Mehul Reuben Das",
                                 published_date: "2023-04-05 08:14:07",
                                 link: "https://www.firstpost.com/world/apple-teases-its-first-official-apple-store-in-india-flagship-store-to-open-in-mumbais-bkc-12410452.html",
                                 clean_url: "firstpost.com",
                                 excerpt: "Apple has teased the first flagship store that they are planning to open in India. The first Apple Store in India will open in Bandra Kurla Complex, or BKC, Mumbai, at the Jio World Drive Mall. A…",
                                 summary: "Apple has teased the first flagship store that they are planning to open in India. The first Apple Store in India will open in Bandra Kurla Complex, or BKC, Mumbai, at the Jio Drive Mall. A second, smaller store will also be opened in Delhi. The much-anticipated Apple Store in India is nearly here. So far, Apple has not stated explicitly where the first Apple Store in India will be located. However, in the guise of a formal ‘teaser,' Apple has now revealed the site of the first Store.  Apple has unveiled the design of its first retail shop, which will be located in Mumbai's Bandra Kurla Complex.",
                                 topic: "news",
                                 country: "IN",
                                 language: "en",
                                 media: "https://images.firstpost.com/wp-content/uploads/2023/04/Apple-teases-its-first-official-Apple-Store-in-India-flagship-store-to-open-in-Mumbais-BKC.jpg")
    
    static let sampleHeadline1 = Article(title: "WHO warns of surge in dengue, chikungunya cases",
                                  author: "Le Monde with AFP",
                                  published_date: "2023-04-05 18:52:39",
                                  link: "https://www.lemonde.fr/en/international/article/2023/04/05/who-warns-of-surge-in-dengue-chikungunya-cases_6021858_4.html",
                                  clean_url: "lemonde.fr",
                                  excerpt: "The United Nations agency responsible for international public health says dengue and other diseases caused by mosquito-borne arboviruses are spreading faster and further as a result of climate…",
                                  summary: "A tiger mosquito ROGER ERITJA/BIOSPHOTO The World Health Organization warned on Wednesday, April 5, that dengue and other diseases caused by mosquito-borne arboviruses were spreading far faster and further as a result of climate change, warning global outbreaks could be looming. Experts with the WHO sounded the alarm over swelling numbers of cases of dengue and chikungunya and cautioned against new epidemics of zika that could also be expected in the coming months. All three are caused by arboviruses carried by Aedes aegypti mosquitos, which have been spreading into new territory as the planet warms.",
                                  topic: "news",
                                  country: "FR",
                                  language: "en",
                                  media: "https://img.lemde.fr/2022/07/01/0/8/4272/2848/1440/960/60/0/46eb983_1656687692661-bios-1796371.jpg")
    
    static let sampleHeadline2 = Article(title: "L'OMC prévoit un ralentissement du commerce mondial en 2023",
                                  author: "Julien Bouissou",
                                  published_date: "2023-04-05 17:51:26",
                                  link: "https://www.lemonde.fr/economie/article/2023/04/05/l-omc-prevoit-un-ralentissement-du-commerce-mondial-en-2023_6168438_3234.html",
                                  clean_url: "lemonde.fr",
                                  excerpt: "La hausse de l'inflation, le durcissement des politiques monétaires et la montée des tensions géopolitiques vont peser sur la dynamique des échanges, selon l'Organisation mondiale du commerce.",
                                  summary: "La prévision de croissance du commerce mondial pour 2023, dévoilée mercredi 5 avril, est plutôt rassurante si on la compare aux pronostics pessimistes de ces derniers mois, et décevante si on la met en perspective avec la moyenne de ces dernières années. Les économistes de l'Organisation mondiale du commerce (OMC) sont en tout cas bien plus optimistes qu'en octobre 2022 puisqu'ils tablent sur une croissance du commerce de marchandises en volume de 1,7 % en 2023, contre seulement 1 % auparavant. Un changement dû principalement aux meilleures perspectives de croissance du produit intérieur brut dans l'Union européenne (en hausse de 0,7 point de pourcentage), ce qui devrait accélérer la hausse des échanges sur le Vieux Continent.",
                                  topic: "news",
                                  country: "FR",
                                  language: "fr",
                                  media: "https://img.lemde.fr/2021/06/21/0/55/5317/3545/1440/960/60/0/19566b8_860674604-gtfreectr.jpg")
    
    static let sampleHeadline3 = Article(title: "Cindy McCain prend la direction d'un Programme alimentaire mondial en surchauffe",
                                  author: "Mathilde Gérard",
                                  published_date: "2023-04-05 17:10:54",
                                  link: "https://www.lemonde.fr/planete/article/2023/04/05/cindy-mccain-prend-la-direction-d-un-programme-alimentaire-mondial-en-surchauffe_6168434_3244.html",
                                  clean_url: "lemonde.fr",
                                  excerpt: "Veuve de John McCain et ambassadrice des Etats-Unis depuis 2021, la nouvelle directrice du PAM aura pour tâche, notamment, de lever des fonds en pleine crise alimentaire mondiale.",
                                  summary: "Cindy McCain (au centre) et la délégation du Congrès américain, ainsi que la représentante du PAM en Zambie, Cissy Byenkya, dans le district de Kazungula, en Zambie, le 20 février 2023. NKOLE MWAPE/WFP Une Américaine, républicaine, remplace un Américain, républicain. Arrivé au bout de son mandat de six ans à la tête du Programme alimentaire mondial (PAM), David Beasley (ancien gouverneur de Caroline du Sud) a passé la main, mardi 4 avril, à Cindy McCain, ambassadrice des Etats-Unis depuis 2021 auprès des « agences romaines », les trois agences de l'ONU dédiées à l'agriculture et à l'alimentation (PAM, FAO et le Fonds international pour le développement agricole, FIDA), et veuve de l'ancien sénateur républicain de l'Arizona, John McCain.",
                                  topic: "world",
                                  country: "FR",
                                  language: "fr",
                                  media: "https://img.lemde.fr/2023/04/05/244/0/5250/3500/1440/960/60/0/2b2a4ef_1680711596621-wf1738152-20230220-zmb-nkole-mwape-0015.jpg")
    
    static let sampleHeadline4 = Article(title: "Yacht et train blindé : les confidences d'un officier du service de sécurité de Poutine qui a fait défection",
                                  author: "Benoît Vitkine",
                                  published_date: "2023-04-05 16:40:04",
                                  link: "https://www.lemonde.fr/international/article/2023/04/05/yacht-et-train-blinde-les-confidences-d-un-officier-du-service-de-securite-de-poutine-qui-a-fait-defection_6168429_3210.html",
                                  clean_url: "lemonde.fr",
                                  excerpt: "Gleb Karakoulov a profité d'une mission au Kazakhstan, mi-octobre 2022, pour fuir. Son témoignage, recueilli par un média russe dissident, confirme le luxe, la « bulle informationnelle » et la…",
                                  summary: "Gleb Karakoulov lors d'une interview donnée en Turquie, en décembre 2022. (Dossier Center via AP) AP Il s'agit de la défection la plus importante connue au sein des services russes de sécurité depuis le début de « l'opération militaire spéciale » en Ukraine. Gleb Karakoulov, capitaine du Service fédéral de protection (FSO), a réussi à se réfugier à Istanbul à l'occasion d'une mission au Kazakhstan, mi-octobre 2022. Dossier Center , un média de l'ancien oligarque Mikhaïl Khodorkovski, qui publie son témoignage, détaille les différents éléments confirmant son appartenance à ce service de sécurité chargé de la protection des personnalités, et en particulier du président et du premier ministre.",
                                  topic: "world",
                                  country: "FR",
                                  language: "fr",
                                  media: "https://img.lemde.fr/2023/04/05/0/0/1999/1333/1440/960/60/0/eaee607_1680711506305-347346.jpg")
    
    static let sampleHeadline5 = Article(title: "Tiago Rodrigues déploie les nouveaux paysages du Festival d'Avignon",
                                  author: "Fabienne Darge",
                                  published_date: "2023-04-05 16:30:07",
                                  link: "https://www.lemonde.fr/culture/article/2023/04/05/tiago-rodrigues-deploie-les-nouveaux-paysages-du-festival-d-avignon_6168426_3246.html",
                                  clean_url: "lemonde.fr",
                                  excerpt: "Pour sa première programmation, le nouveau directeur qui a succédé à Olivier Py confie l'ouverture à la metteuse en scène Julie Deliquet et proposera 12 000 places de plus à la vente.",
                                  summary: "Tiago Rodrigues, à la FarbricA, à Avignon, le 5 avril 2023. CHRISTOPHE RAYNAUD DE LAGE/FESTIVAL D'AVIGNON Un nouveau paysage se dessine à Avignon, riche de promesses et de découvertes : Tiago Rodrigues, le directeur du Festival, a annoncé, mercredi 5 avril dans la cité des Papes, le programme de sa première édition (et 77 e du nom depuis la fondation de la manifestation par Jean Vilar en 1947), qui se déroulera du 5 au 25 juillet. Un geste inaugural qui ne se prétend pas révolutionnaire, mais entend faire bouger les lignes en douceur, ouvrir de nouvelles pistes, défricher des sentiers de déambulation partagée, retrouver des chemins oubliés.",
                                  topic: "entertainment",
                                  country: "FR",
                                  language: "fr",
                                  media: "https://img.lemde.fr/2023/04/05/227/0/2001/1334/1440/960/60/0/ad22959_1680707300757-230405-rdl-0163.jpg")
    
    static let sampleHeadline6 = Article(title: "ChatGPT : premières plaintes auprès de la CNIL contre le logiciel d'intelligence artificielle",
                                  author: "Le Monde avec AFP",
                                  published_date: "2023-04-05 16:30:05",
                                  link: "https://www.lemonde.fr/pixels/article/2023/04/05/chatgpt-premieres-plaintes-aupres-de-la-cnil-contre-le-logiciel-d-intelligence-artificielle_6168425_4408996.html",
                                  clean_url: "lemonde.fr",
                                  excerpt: "La CNIL a reçu deux plaintes mardi portant sur l'utilisation des données personnelles par ChatGPT, outil numérique désormais bloqué en Italie.",
                                  summary: "Au moins deux plaintes portant sur l'utilisation des données personnelles ont été déposées en France contre le robot conversationnel ChatGPT , déjà visé par diverses procédures dans plusieurs pays, a appris mercredi 5 avril l'Agence France-Presse (AFP) auprès des plaignants. Ces deux plaintes, révélées par L'Informé , ont été déposées mardi auprès de la Commission nationale de l'informatique et des libertés (CNIL), le gendarme français des données personnelles. La première provient de l'avocate Zoé Vilain, présidente de l'association de sensibilisation aux enjeux du numérique Janus International.",
                                  topic: "news",
                                  country: "FR",
                                  language: "fr",
                                  media: "https://img.lemde.fr/2023/04/05/0/0/8149/5433/1440/960/60/0/5bf2041_5939603-01-06.jpg")
    
    static let sampleHeadline7 = Article(title: "Sibyle Veil, présidente de Radio France : « Mon rôle est de proposer une alternative » aux « fake news », aux photos et aux vidéos manipulées",
                                  author: "Aude Dassonville",
                                  published_date: "2023-04-05 16:00:30",
                                  link: "https://www.lemonde.fr/economie/article/2023/04/05/sibyle-veil-presidente-de-radio-france-mon-role-est-de-proposer-une-alternative-aux-fake-news-aux-photos-et-aux-videos-manipulees_6168423_3234.html",
                                  clean_url: "lemonde.fr",
                                  excerpt: "Pour la présidente de Radio France, « les dérives de ces dernières années ne sont rien face au tsunami que l'on connaîtra demain ». « L'enjeu de la confiance est primordial », affirme-t-elle.",
                                  summary: "Sibyle Veil, PDG de Radio France, à Paris, le 22 février 2022. ED ALCOCK/MYOP Alors que les entreprises de l'audiovisuel public échangent actuellement avec le ministère de la culture autour de leur futur contrat d'objectifs et de moyens (COM), qui fixera leurs axes prioritaires de développement et les perspectives économiques pour les cinq prochaines années, Sibyle Veil entamera, le 16 avril, son second mandat à la tête de Radio France. Sans connaître encore sa trajectoire financière ni son mode de financement, mais avec l'objectif de conserver des contenus et des audiences solides.",
                                  topic: "economics",
                                  country: "FR",
                                  language: "fr",
                                  media: "https://img.lemde.fr/2023/04/05/1307/0/4480/2986/1440/960/60/0/4669d76_1680707840225-myop-myop-ea-sibyleveil-012.JPG")
    
    static let sampleHeadline8 = Article(title: "JO de Paris 2024 : « L'inclusion par le sport fonctionne très bien »",
                                  author: "Laura Pottier",
                                  published_date: "2023-04-05 16:00:25",
                                  link: "https://www.lemonde.fr/sport/article/2023/04/05/jo-de-paris-2024-l-inclusion-par-le-sport-fonctionne-tres-bien_6168421_3242.html",
                                  clean_url: "lemonde.fr",
                                  excerpt: "Le CREPS Ile-de-France, à Châtenay-Malabry, mobilise cette semaine 200 encadrants pour accueillir six classes par jour dans le cadre de la semaine olympique et paralympique. Elèves valides et en…",
                                  summary: "Dans les allées du (Hauts-de-Seine), impossible de ne pas apercevoir des groupes de jeunes avec leurs t-shirts colorés et cette inscription dans leur dos : « SOP - Semaine olympique et paralympique ». En ce mardi 4 avril, le Centre de ressources d'expertise et de performance sportive, établissement public de formation (au haut niveau mais aussi aux métiers du sport et d'animation), accueille, comme chaque jour depuis lundi et jusqu'à vendredi, six classes de la région francilienne dans le cadre de cette SOP, qui a lieu tous les ans depuis 2017.",
                                  topic: "sport",
                                  country: "FR",
                                  language: "fr",
                                  media: "https://img.lemde.fr/2023/04/05/0/0/3189/2126/1440/960/60/0/5832b35_1680685102447-7-img-2465-millerand.jpg")
    
    static let sampleHeadline9 = Article(title: "JO de Paris 2024 : en matière d'accessibilité, « la réalité n'est pas jolie »",
                                  author: "Laura Pottier",
                                  published_date: "2023-04-05 16:00:21",
                                  link: "https://www.lemonde.fr/sport/article/2023/04/05/jo-de-paris-2024-en-matiere-d-accessibilite-la-realite-n-est-pas-jolie_6168418_3242.html",
                                  clean_url: "lemonde.fr",
                                  excerpt: "Patrice Tripoteau, directeur général adjoint de APF France handicap, considère que les difficultés rencontrées dans le cadre de l'organisation des Jeux, sur le transport ou le logement , « sont…",
                                  summary: "A presque 500 jours des Jeux paralympiques, Patrice Tripoteau, directeur général adjoint de APF France handicap, alerte sur la situation actuelle en matière d'accessibilité pour les personnes en situation de handicap. La semaine olympique et paralympique (du 3 au 8 avril) est organisée cette année autour du thème de l'inclusion par la pratique sportive. Quelle est la réalité aujourd'hui pour les personnes en situation de handicap qui souhaitent faire du sport ? Il y a un premier frein qui est la barrière qu'elles se mettent elles-mêmes : très souvent, elles n'ont même pas l'idée de faire une activité physique car elles pensent qu'elles n'en sont pas capables.",
                                  topic: "sport",
                                  country: "FR",
                                  language: "fr",
                                  media: "https://img.lemde.fr/2023/04/05/279/121/4561/3041/1440/960/60/0/d4ee6de_1680699351553-000-par7479011.jpg")
    
    static let sampleHeadline10 = Article(title: "Il y a 255 millions d'années, des amphibiens nageaient comme les crocodiles",
                                   author: "Jean-Baptiste Jacquin",
                                   published_date: "2023-04-05 16:00:13",
                                   link: "https://www.lemonde.fr/sciences/article/2023/04/05/il-y-a-255-millions-d-annees-des-amphibiens-nageaient-comme-les-crocodiles_6168417_1650684.html",
                                   clean_url: "lemonde.fr",
                                   excerpt: "Les dernières technologies d'imagerie ont permis d'interpréter des traces fossilisées laissées par des sortes de salamandres préhistoriques en Afrique du Sud.",
                                   summary: "A gauche : empreinte trouvée sur la paléosurface Dave Green, en Afrique du Sud. A droite : trace laissée par un Alligator mississippiensis actuel en Géorgie (Etats-Unis). ST. CATHERINES ISLAND SEA TURTLE PROGRAM, GALE A. BISHOP C'est une célèbre surface rocheuse plane, qui était autrefois le fond d'un estran à marée basse ou d'un lagon peu profond, dans l'actuel Kwazulu-Natal, une province côtière d'Afrique du Sud. Célèbre pour les paléontologues, car elle contient de nombreux fossiles et traces de tétrapodes (animaux à quatre pattes), de poissons et d'invertébrés.",
                                   topic: "science",
                                   country: "FR",
                                   language: "fr",
                                   media: "https://img.lemde.fr/2023/04/03/0/38/1950/1300/1440/960/60/0/e209acd_1680517671054-journal-pone-0282354-g010-copie.jpg")
    
    static var sampleArticles = [sampleArticle1, sampleArticle2, sampleArticle3]
    
    static var sampleHeadlines = [sampleHeadline1, sampleHeadline2, sampleHeadline3, sampleHeadline4, sampleHeadline5, sampleHeadline6, sampleHeadline7, sampleHeadline8, sampleHeadline9, sampleHeadline10]
    
    static var sampleSources = [
        "alpenhornnews.com",
        "forbes.com",
        "businessinsider.com",
        "prnewswire.com",
        "einpresswire.com",
        "greenwichtime.com",
        "sfchronicle.com",
        "sfgate.com",
        "theintelligencer.com",
        "lakecountystar.com",
        "mrt.com",
        "sheltonherald.com",
        "lmtonline.com",
        "milfordmirror.com",
        "newstimes.com",
        "thetelegraph.com",
        "beaumontenterprise.com",
        "benzinga.com",
        "middletownpress.com",
        "ctpost.com",
        "nhregister.com",
        "thehour.com",
        "timesunion.com",
        "michigansthumb.com",
        "ourmidland.com",
        "registercitizen.com",
        "stamfordadvocate.com",
        "myjournalcourier.com",
        "seattlepi.com",
        "mysanantonio.com",
        "chron.com",
        "yahoo.com",
        "fortune.com",
        "seattletimes.com",
        "wiltonbulletin.com",
        "trumbulltimes.com",
        "theridgefieldpress.com",
        "apnews.com",
        "khon2.com",
        "kxan.com",
        "bigrapidsnews.com",
        "darientimes.com",
        "wric.com",
        "legacy.com",
        "ncadvertiser.com",
        "bloomberg.com",
        "click2houston.com",
        "compsmag.com",
        "pahomepage.com",
        "houstonchronicle.com",
        "ksn.com",
        "sandiegouniontribune.com",
        "theheraldreview.com",
        "wgno.com",
        "cnn.com",
        "fox4kc.com",
        "ksat.com",
        "8newsnow.com",
        "blackenterprise.com",
        "cbs42.com",
        "fastcompany.com",
        "myplainview.com",
        "ourquadcities.com",
        "wjbf.com",
        "cnbc.com",
        "manisteenews.com",
        "wbtw.com",
        "wnct.com",
        "businessjournaldaily.com",
        "businessrecord.com",
        "conchovalleyhomepage.com",
        "globenewswire.com",
        "inc.com",
        "movieweb.com",
        "mychamplainvalley.com",
        "seekingalpha.com",
        "wboy.com",
        "wearegreenbay.com",
        "wjhl.com",
        "wspa.com",
        "abc4.com",
        "businessreport.com",
        "clickondetroit.com",
        "swoknews.com",
        "wcia.com",
        "broadwayworld.com",
        "coindesk.com",
        "fourstateshomepage.com",
        "fox40.com",
        "kfor.com",
        "kget.com",
        "kxnet.com",
        "latimes.com",
        "tastingtable.com",
        "wgnradio.com",
        "wpri.com",
        "yourcentralvalley.com",
        "clarksvillenow.com",
        "deadline.com",
        "expressnews.com"
    ]
}
#endif
